---

workspace:
  base: /go
  path: src/github.com/packethost/cacher

default_deploy: &default_deploy
  group: deploy
  image: quay.io/packet/packet-nomad:v1
  pull: true
  commands:
    - deploy/deploy
  secrets:
    - nomad_addr
    - quay_password
    - quay_user
  when:
    event: push
    branch:
      - master
default_deploy_env: &default_deploy_env
  NOMAD_DEPLOY_ENV: production
  NOMAD_DEPLOY_NAME: cacher
  NOMAD_DEPLOY_ENV_FILE: deploy/env
  NOMAD_DEPLOY_IMAGE: quay.io/packet/cacher:${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
  NOMAD_DEPLOY_RESOURCE_CPU: "50"
  NOMAD_DEPLOY_RESOURCE_MEM: "48"
  NOMAD_DEPLOY_WORKERS: "1"

pipeline:
  lint:
    group: ci
    image: golang:1.10-alpine
    commands:
      - apk add --update --upgrade --no-cache git
      - go get -v -u github.com/alecthomas/gometalinter
      - gometalinter --install
      - gometalinter --errors --vendor --vendored-linters ./...
      - gofmt -d *.go | (! grep '.')

  test:
    group: ci
    image: golang:1.10-alpine
    commands:
      - go test -v ./...

  build:
    group: ci
    image: golang:1.10-alpine
    commands:
      - CGO_ENABLED=0 go build -ldflags="-X main.gitrev=${DRONE_COMMIT_SHA}" -o cacher-linux-x86_64

  publish:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/packet/cacher
    tags:
      - ${DRONE_BRANCH/\//-}
      - ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
    when:
      event: push
    secrets: [docker_username, docker_password]

  publish_tag:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/packet/cacher
    tags: ${DRONE_TAG}
    when:
      event: tag
    secrets: [docker_username, docker_password]

  deploy-staging:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: ewr1
      NOMAD_DEPLOY_ENV: staging

  deploy-syd2:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: syd2

  deploy-bos2:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: bos2

  deploy-ord2:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: ord2

  deploy-ord3:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: ord3

  deploy-ord4:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: ord4

  deploy-phx1:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: phx1

  deploy-sea2:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: sea2

  deploy-atl2:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: atl2

  deploy-pit1:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: pit1

  deploy-labng1:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: labng1

  deploy-lax2:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: lax2

  deploy-iad2:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: iad2

  deploy-att-poc1:
    <<: *default_deploy
    when:
      event: deployment
      environment:
        - att-production
        - att-production-att-poc1
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: att-poc1

  deploy-sin3:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: sin3

  deploy-dtw1:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: dtw1

  deploy-iah1:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: iah1

  deploy-mci1:
    <<: *default_deploy
    environment:
      <<: *default_deploy_env
      NOMAD_DEPLOY_SITE: mci1
