---

workspace:
  base: /go
  path: src/github.com/packethost/cacher

pipeline:
  lint:
    group: ci
    image: golang:1.10-alpine
    commands:
      - apk add --update --upgrade --no-cache git
      - go get -v -u github.com/alecthomas/gometalinter
      - gometalinter --install
      - gometalinter --errors --vendor --vendored-linters ./...
      - gofmt -d *.go | (! grep '.')

  test:
    group: ci
    image: golang:1.10-alpine
    commands:
      - go test -v ./...

  build:
    group: ci
    image: golang:1.10-alpine
    commands:
      - CGO_ENABLED=0 go build -ldflags="-X github.com/packethost/cacher/version.GitRev=${DRONE_COMMIT_SHA}"

  publish_cacher_build:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/packet/cacher
    tags: ${DRONE_BRANCH/\//-}
    when:
      event: [push]
    secrets: [docker_username, docker_password]

  publish_db_build:
    group: publish
    image: plugins/docker
    context: db
    dockerfile: db/Dockerfile
    registry: quay.io
    repo: quay.io/packet/cacher-db
    tags: ${DRONE_BRANCH/\//-}
    when:
      event: [push]
    secrets: [docker_username, docker_password]

  publish_cacher_tag:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/packet/cacher
    tags: ${DRONE_TAG}
    when:
      event: [tag]
    secrets: [docker_username, docker_password]

  publish_db_tag:
    group: publish
    image: plugins/docker
    context: db
    dockerfile: db/Dockerfile
    registry: quay.io
    repo: quay.io/packet/cacher-db
    tags: ${DRONE_TAG}
    when:
      event: [tag]
    secrets: [docker_username, docker_password]
