workspace:
  base: /go
  path: src/github.com/packethost/cacher

pipeline:
  lint:
    group: ci
    image: golang:1.9-alpine
    commands:
      - apk add --update --upgrade --no-cache git
      - go get -v -u github.com/alecthomas/gometalinter
      - gometalinter --install
      - gometalinter --errors --vendor --vendored-linters ./...
      - gofmt -d *.go | (! grep '.')

  test:
    group: ci
    image: golang:1.9-alpine
    commands:
      - go test -v ./...

  build:
    group: ci
    image: golang:1.9-alpine
    commands:
      - CGO=0 go build

  publish_latest:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/packet/cacher
    tags: latest
    when:
      event: [push]
    secrets: [ docker_username, docker_password ]

  publish_tag:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/packet/cacher
    tags: ${DRONE_TAG}
    when:
      event: [tag]
    secrets: [ docker_username, docker_password ]
