---

workspace:
  base: /go
  path: src/github.com/packethost/cacher

pipeline:
  lint:
    group: ci
    image: golang:1.10-alpine
    commands:
      - apk add --update --upgrade --no-cache git
      - go get -v -u github.com/alecthomas/gometalinter
      - gometalinter --install
      - gometalinter --errors --vendor --vendored-linters ./...
      - gofmt -d *.go | (! grep '.')

  test:
    group: ci
    image: golang:1.10-alpine
    commands:
      - go test -v ./...

  build:
    group: ci
    image: golang:1.10-alpine
    commands:
      - CGO_ENABLED=0 go build -ldflags="-X main.gitrev=${DRONE_COMMIT_SHA}" -o cacher-linux-x86_64

  publish:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/packet/cacher
    tags:
      - ${DRONE_BRANCH/\//-}
      - ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
    when:
      event: [push]
    secrets: [docker_username, docker_password]

  publish_tag:
    group: publish
    image: plugins/docker
    registry: quay.io
    repo: quay.io/packet/cacher
    tags: ${DRONE_TAG}
    when:
      event: [tag]
    secrets: [docker_username, docker_password]

  deploy-db-staging:
    image: quay.io/packet/packet-nomad:v1
    commands:
      - >-
        packet-nomad
        --addr $NOMAD_ADDR
        deploy
        --env $ENV
        --name $SERVICE
        --image quay.io/packet/$SERVICE:${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
        --site ewr1
        --resource_cpu 50
        --resource_mem 48
        --workers 1
        --job-type batch
        --batch-name 'migrate'
        --cmd '/migrate'
        --env-file 'deploy/staging-env'
    secrets: [nomad_addr, quay_user, quay_password]
    environment:
      DEPLOY_VERSION: ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
      ENV: staging
      SERVICE: cacher
    when:
      event: [push]
      # branch: [master]

  deploy-app-staging:
    image: quay.io/packet/packet-nomad:v1
    commands:
      - >-
        packet-nomad
        --addr $NOMAD_ADDR
        deploy
        --env $ENV
        --name $SERVICE
        --image quay.io/packet/$SERVICE:${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
        --site ewr1
        --resource_cpu 50
        --resource_mem 48
        --workers 1
        --internal-http-service $SERVICE-$ENV.packet.net
        --internal-grpc-service $SERVICE-$ENV.packet.net
        --env-file 'deploy/staging-env'
    secrets: [nomad_addr, quay_user, quay_password]
    environment:
      DEPLOY_VERSION: ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
      ENV: staging
      SERVICE: cacher
    when:
      event: [push]
      # branch: [master]

  verify-staging:
    image: quay.io/packet/packet-nomad:v1
    commands:
      - deploy/verify_url.sh http://$SERVICE-$ENV.packet.net/_packet/healthcheck
    environment:
      ENV: staging
      SERVICE: cacher
    when:
      event: [push, tag]
      branch: [master]
